name: C/C++ CI

on:
  push:
    branches-ignore:
      - "test---build"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
      - name: Merge into test---build on success
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/test---build' }}
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          set -e
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git fetch origin
          if git ls-remote --exit-code --heads origin test---build >/dev/null 2>&1; then
            git checkout -B test---build origin/test---build
          else
            git checkout -b test---build
          fi
          git merge --no-ff --no-edit "origin/${{ github.ref_name }}"
          git push origin test---build
